### ISSUE TITLE
Add functionality to allow user download over a range of dates and to a specific location

### ISSUE THREAD

**Issue by econpotter** [rbturnbull/ausdex#10]
The package suggests that it provides user access to data, and it does, but a key use for my workflow would be to download the raw data itself, because I want to have access to those numbers if I need to replicate something.

It looks like currently `ausdex.cached_download()` is the option to download, but a user-specific method that allows for downloading the CPI data over a range of dates and into a specific folder would be useful. Adding this to the usage documentation would also be helpful.

**Comment by rbturnbull** [comment]
Yeah, that's a much better idea. I've refactored to put all the downloading code into files.py. There is now a function `cached_download_cpi` which allows the user to download to a specified local path if given. You can also set the date explicitly. This function and all others in files.py are now added to the API section of the docs here: https://rbturnbull.github.io/ausdex/reference.html#module-ausdex.files
