### ISSUE TITLE
CPI data only goes up to June2022

### ISSUE THREAD

**Issue by alexa-malexa** [rbturnbull/ausdex#14]
Hi, I noticed the CPI data only goes to June2022, any plans to update this? Thank you

**Comment by rbturnbull** [comment]
Hi @alexa-malexa  - thanks very much for bringing this to our attention. The ABS changed their URL scheme for releases at the end of last year. I've changed the code to reflect the new scheme. It should work now with the Dec 2022 release. I'll check again when the March 2023 data is released. The code in github now should work properly and also the release at PyPI.

**Comment by alexa-malexa** [comment]
Much appreciated, thanks!
