### ISSUE TITLE
Problem with the CLI usage

### ISSUE THREAD

**Issue by konstantinstadler** [rbturnbull/ausdex#2]
Hi,

This is connected to the JOSS review.
I tested all examples given in the README and most work. However, if I do  

`$ ausdex seifa-vic 2020 footscray ier_score`

I receive NaN. Full output:

```
UserWarning: The Shapely GEOS version (3.10.2-CAPI-1.16.0) is incompatible with the GEOS version PyGEOS was compiled with (3.9.1-CAPI-1.14.2). Conversions between both will be slow.
nan
```

One other oberservations: The interpolate_vic_suburb_seifa values given in the README for the interactive use are 2 units above the values I currently get. Probably due to updates in the upstream db.

**Comment by rbturnbull** [comment]
Moved over to the new seifa repository: https://github.com/sailngarbwm/seifa/issues/3
