### ISSUE TITLE
Please add some contribution infos

### ISSUE THREAD

**Issue by konstantinstadler** [rbturnbull/ausdex#4]
Please add some contribution information to your readme or, prefered, to a specific CONTRIBUTION.md file.
This should include details on :

- do you accept outside contribution?
- if yes, what is the scope for these
- if yes, in which form/what is the workflow
- if yes: coding style/format, required tests, ...

You have some of that already in the "Development" section of the readme, but that would need to be extended.

There are tons of examples on various open-source github repos, some first pointers:

- http://mozillascience.github.io/working-open-workshop/contributing/
- https://cookiecutter.readthedocs.io/en/1.7.1/CONTRIBUTING.html
- https://gist.github.com/PurpleBooth/b24679402957c63ec426

**Comment by rbturnbull** [comment]
Thanks for the suggestions here. I've added in a CONTRIBUTING.md file with the Contributor Covenant as the code of conduct. I've also included it in the documentation: https://rbturnbull.github.io/ausdex/contributing.html

I'll close this issue but if I'm happy to add other things into CONTRIBUTING.md as required.
