### ISSUE TITLE
Magic numbers in the code

### ISSUE THREAD

**Issue by konstantinstadler** [rbturnbull/ausdex#6]
The function (in data_io.py)

```
def download_from_aurin(
    wfs_aurin, dataset, links, local_path, bbox=(96.81, -43.75, 159.11, -9.14)
):

```
has these 4 magic numbers which should be explained in a docstring or stored in a meaningful variable name.

**Comment by rbturnbull** [comment]
I've replicated this issue in the repository for the new seifa package: https://github.com/sailngarbwm/seifa/issues/1
