### ISSUE TITLE
Add additional detail to the installation section of documentation

### ISSUE THREAD

**Issue by econpotter** [rbturnbull/ausdex#7]
The installation currently does not note that `ausdex` only works with Python versions `>=3.7, <3.10`. A sentence or two about these limitations would be helpful.

As an example, I am working from a newer laptop that only has 3.10 installed, and installation errors were not indicative of these version limitations. I had to try the poetry installation to find these version limitations, and then install python 3.7.

**Comment by rbturnbull** [comment]
I'll make it so that it is compatible with python 3.10 as per issue #8. When we started the package last year, one of the dependencies required python<3.10 but now that is no longer required.

**Comment by rbturnbull** [comment]
Closing because the new version is compatible with python 3.10 and it has been released to PyPI. There is a note in the documentation that it needs python >=3.8.
